### ISSUE TITLE
Compatibility with CM12?

### ISSUE THREAD

**Issue by RealRancor** [enricocid/JellyRevenge-CM11-theme#2]
Hi,

first thanks for your theme. Loved it in CM11. But it seems some changes are now needed to make themes compatible with the new Holo Design:

https://plus.google.com/117889454318656086861/posts/ZTk2TAdi7NM

Any changes to get an CM12 compatible version of your theme?

**Comment by enricocid** [comment]
I'm on stock lollipop 5.1 right now and I have no intention of flashing custom roms (so I can't test it).
If You want You can ask on XDA or G+ communities.

**Comment by RealRancor** [comment]
Hi,

fair enough. Thanks for the info. :+1:

**Comment by enricocid** [comment]
I've flashed a custom rom, gonna try to port the theme to cm12 theme manager since lollipop stock theme s**** :)

**Comment by RealRancor** [comment]
Hey,

great news. :)

> since lollipop stock theme s**** :)

Absolutely agree. One of the main reasons of my initial question here. :)

**Comment by varyoo** [comment]
The theme was fun, waiting too!
